# Generated by Django 4.2.2 on 2024-07-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="publication",
            field=models.BooleanField(default=False, verbose_name="Опубликовано"),
        ),
    ]
