# Generated by Django 4.2.2 on 2024-07-16 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["category", "name"],
                "permissions": [
                    ("can_cancel_publication", "может отменять публикацию продукта"),
                    (
                        "can_change_description ",
                        "может менять описание любого продукта",
                    ),
                    ("can_cancel_category", "может менять категорию любого продукта"),
                ],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
    ]
